tool_box: "TyMachinelearning"
class: "Classification"
sub_class: "Classifierensemble"

function: 
  name: "AdaboostTree"
  short_description: "阿达分类树模型"

usages: 
  - usage: "返回基于输入数据 X 和弱模型基数 n_estimators 的阿达分类树模型。"
    outputs: 
      - name: "mdl"
      # - name: "mdl"
    inputs: 
      - name: "X"
      - name: "n_estimators"
      - name: "learn_rate"

examples:
  - example:
    name: 训练判别分析模型

inputs:
  - arg: "X"
    short_description: "预测数据"
    long_description: "预测数据，指定为Dataframe。X 的每一行对应一个观测值，每一列对应一个预测变量。最后一行为标签。"
    type: "Dataframe"
    type_zh: "Dataframe"
  - arg: "n_estimators"
    short_description: "弱模型基数"
    long_description: "对应弱模型的基数数量。"
    type: "Int64"
    type_zh: "数值"
  - arg: "max_depth"
    short_description: "模型最大深度"
    long_description: "最大深度默认值为9"
    type: "Int64"
    type_zh: "数值"
  - arg: "min_samples_leaf"
    short_description: "模型最小枝叶"
    long_description: "模型最小枝叶默认值为1"
    type: "Int64"
    type_zh: "数值"

outputs:
  - arg: "mdl"
    short_description: "输出值"
    long_description: "经过训练的判别分析分类模型，作为分类判别模型对象返回。"
    type: ""
    type_zh: "判别分析对象"
