tool_box: "ToolBoxName"  # 工具箱的名称
class: "ClassName"  # 大分类
sub_class: "SubClassName"  # 小分类
# sub_sub_class: "....."  # 小小分类

function: 
  name: "function_name"  # 函数的名称
  short_description: "这是一个函数"  # 函数的简短介绍（位于网页首部函数名下方的小字）

usages:  # 函数的调用方式，可以有多个，使用 - usage 分隔
  - usage: "这个函数的详细介绍就写在这里，对应的就是网页版本中，说明栏目每一个用法后面的详细文字说明。如果文字需要换行，使用 `\\n\\n` 来进行换行。\n\n比如说这样。"  # 使用方式说明，位于说明栏目的表达式后面的文字说明
    outputs:  # 输出参数，可以有多个，使用 - name 分隔
      - name: "output_0"  # 参数的名称
      # - name: "output_1"
    inputs:  # 输入参数，可以有多个，使用 - name 分割
      - name: "input_0"
      # - name: "input_1"
  - usage: "这个说明只是一个示例，现在是第二种用法的说明。这里就介绍一下 `Name=Value` 的配置规范。"
    outputs: 
      - name: "output_0"
    inputs:  # 名称-值对参数的格式，第一个参数为四个下划线 "____", 第二个参数为 "Name=Value"
      - name: "____"  
      - name: "Name=Value"  

examples:  # 用例，可以有多个，使用 - example 分隔
  - example:  # 一个用例
    name: 用例的标题  # 用例的标题
  # - example: 
  #   name: 后续的用例

inputs:  # 输入参数的详细解释，可以有多个，使用 - arg 分隔
  - arg: "input_0"  # 参数名称
    short_description: "第一个输入参数"  # 简介（在网页中对应参数后面紧接着的简短解释，比如：**X - 预测数据**）
    long_description: "这里是第一个参数的详细文字介绍，这里的参数和上面 `usages -> usage -> inputs -> name` 里面的参数一致哈。"  # 详细介绍
    type: "AType"  # 显示在介绍栏目底部的数据类型
    type_zh: "一个类型"  # 显示在标题下面的数据类型（一般用中文表示）
  # - arg: "..."
  #   short_description: "..."
  #   long_description: "..."
  #   type: "..."
  #   type_zh: "..."

name_value:  # 名称-值对组参数，可以有多个，使用 - arg 来分隔
  - arg: "arg_0"
    default: 12  # 默认值
    short_description: "可选参数0"
    long_description: "这里是第一个参数的详细文字介绍，我知道，世界上有 25% 的鸡翅来自于 M826 小行星，而其中 1.3% 的翅根流向了 McDxxxxd's，而在这其中，有 99.9% 的鸡翅成为了中国限定的麦辣鸡翅。"
    type: "Int64"
    type_zh: "数值"
  - arg: "arg_1"
    default: 9
    short_description: "可选参数1"
    long_description: "最大深度默认值为9"
    type: "Int64"
    type_zh: "数值"
  # - arg: "..."
  #   default: 1
  #   short_description: "..."
  #   long_description: "..."
  #   type: "..."
  #   type_zh: "..."

outputs:
  - arg: "output_0"
    short_description: "输出值"
    long_description: "这里是第一个参数的详细文字介绍，这里的参数和上面 `usages -> usage -> outputs -> name` 里面的参数一致。"
    type: ""
    type_zh: "数据类型"
  # - arg: "..."
  #   short_description: "..."
  #   long_description: "..."
  #   type: ""
  #   type_zh: "..."
